### ISSUE TITLE
Обновить docker-compose.yml и очистить .env от неиспользуемых переменных

### ISSUE THREAD

**Issue by luxqw** [luxqw/vexel-music-bot#18]
## Текущая проблема

Ваш текущий `.env` файл содержит переменные, которые не используются в коде:

```env
# ❌ Не используется в коде
GUILD_ID=707538993318723604
MUSIC_CONTROL_ROLE=DJ
DEBUG=true
LOG_LEVEL=DEBUG
ENVIRONMENT=development
MAX_QUEUE_SIZE=30
DEFAULT_VOLUME=0.4
ENABLE_DEBUG_COMMANDS=true
ENABLE_METRICS=true
```

### 1. Обновить docker-compose.yml

**Текущий:**
```yaml
services:
  bot:
    image: ghcr.io/luxqw/vexel-music-bot:latest
    container_name: vexel-music-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    working_dir: /app
    restart: unless-stopped
    command: ["python3", "main.py"]
```

**✅ Обновленный:**
```yaml
services:
  bot:
    image: ghcr.io/luxqw/vexel-music-bot:latest
    container_name: vexel-music-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1        # Для правильного отображения логов
      - MAX_PLAYLIST_SIZE=15      # Лимит плейлиста
    volumes:
      - ./bot:/app/bot
      - ./cookies:/app/cookies    # Для YouTube cookies
    working_dir: /app
    restart: unless-stopped
    command: ["python3", "main.py"]
```

### 2. Обновить .env файл

**Удалить неиспользуемые переменные и привести к стандарту:**

```env
# ✅ Основные настройки
DISCORD_TOKEN=MTAyNTA4OTcyMTczNjYyNjI0Ng.GCnewa.aBzbfYusy0sl1mezCWXPfF24lSIiPHA1piouxU
YDL_OPTS='{"format": "bestaudio"}'

# ✅ Настройки плейлистов
MAX_PLAYLIST_SIZE=15

# ✅ YouTube cookies (для age-restricted контента)
YOUTUBE_COOKIES_FILE=/app/cookies/youtube_cookies.txt

# ✅ Настройки разработки (опционально)
PYTHONUNBUFFERED=1
```

### 3. Обновить .env.example

```env
# Основные настройки
DISCORD_TOKEN=your-bot-token-here
YDL_OPTS='{"format": "bestaudio"}'

# Настройки плейлистов
MAX_PLAYLIST_SIZE=15

# YouTube cookies (опционально, для age-restricted контента)
# YOUTUBE_COOKIES_FILE=/app/cookies/youtube_cookies.txt
# YOUTUBE_BROWSER_COOKIES=chrome,Default

# Настройки разработки (опционально)
# PYTHONUNBUFFERED=1
```

## Ответ на вопрос об ограничении очереди

**❌ НЕТ, ограничение очереди НЕ работает!**

В текущем коде есть только ограничение плейлиста (`MAX_PLAYLIST_SIZE=15`), но **НЕТ ограничения на общую очередь**.

### Что происходит сейчас:
1. Пользователь добавляет плейлист 50 треков → добавляется 15 (лимит плейлиста)
2. Пользователь добавляет еще плейлист 50 треков → добавляется еще 15
3. Можно добавлять бесконечно много плейлистов/треков в очередь

### В main.py добавить:

```python
MAX_QUEUE_SIZE = int(os.getenv("MAX_QUEUE_SIZE", "50"))

@tree.command(name="play", description="Воспроизвести музыку или плейлист с YouTube")
async def play(interaction: discord.Interaction, query: str):
    # ... существующий код ...
    
    queue = get_queue(interaction.guild.id)
    
    # ✅ ДОБАВИТЬ ПРОВЕРКУ ЛИМИТА ОЧЕРЕДИ
    if len(queue) >= MAX_QUEUE_SIZE:
        await interaction.response.send_message(
            f"❌ **Очередь переполнена!**\n"
            f"Максимум треков в очереди: {MAX_QUEUE_SIZE}\n"
            f"Сейчас в очереди: {len(queue)} треков",
            ephemeral=True
        )
        return
    
    # При добавлении плейлиста проверять лимит
    if "entries" in info and info["entries"]:
        remaining_slots = MAX_QUEUE_SIZE - len(queue)
        if remaining_slots <= 0:
            await interaction.edit_original_response(
                content="❌ **Очередь полная!** Освободите место перед добавлением."
            )
            return
        
        # Ограничить как по лимиту плейлиста, так и по свободным местам
        max_to_add = min(MAX_PLAYLIST_SIZE, remaining_slots)
        entries_to_process = info["entries"][:max_to_add]
        
        # ... остальной код ...
```

## Рекомендуемые лимиты

```env
MAX_PLAYLIST_SIZE=15    # Лимит треков из одного плейлиста
MAX_QUEUE_SIZE=50       # Лимит общей очереди
```

## Какие переменные реально используются в коде:

✅ **Используются:**
- `DISCORD_TOKEN`
- `YDL_OPTS` 
- `MAX_PLAYLIST_SIZE`
- `YOUTUBE_COOKIES_FILE`
- `YOUTUBE_BROWSER_COOKIES`

❌ **НЕ используются:**
- `GUILD_ID`
- `MUSIC_CONTROL_ROLE`
- `DEBUG`
- `LOG_LEVEL`
- `ENVIRONMENT`
- `MAX_QUEUE_SIZE` (есть в .env, но не используется в коде!)
- `DEFAULT_VOLUME`
- `ENABLE_DEBUG_COMMANDS`
- `ENABLE_METRICS`

## Файлы для изменения

- [ ] `docker-compose.yml` - добавить переменные окружения и volume для cookies
- [ ] `.env` - убрать неиспользуемые переменные
- [ ] `.env.example` - привести к стандарту
- [ ] `main.py` - добавить ограничение очереди (если нужно)

## Приоритет: Средний

Не критично, но важно для поддержки и чистоты кода.
